DROP TABLE IF EXISTS users;

CREATE TABLE users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email      VARCHAR(255) UNIQUE           NOT NULL,
    password   VARCHAR(255)                  NOT NULL,
    enabled    BOOLEAN      DEFAULT TRUE     NOT NULL,
    status     VARCHAR(255) DEFAULT 'ACTIVE' NOT NULL
);
CREATE INDEX ON users (email);

