spring:
  servlet:
    multipart:
      max-file-size: 157286400
      max-request-size: 157286400
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: postgres
    password: postgres

server:
  port: 8090

jwt:
  token:
    secret: jwtappdemo
    expired: 36000000
